name: kankui_app
description: "Kankui - Aplicación para la recuperación de la lengua Kankuamo"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  uuid: ^4.4.0
  sqflite: ^2.3.0
  path: ^1.8.3
  supabase_flutter: ^2.3.0
  connectivity_plus: ^5.0.2  # Para detectar conexión
  get_it: ^7.6.4
  mobile_scanner: ^7.2.0
  qr_flutter: ^4.1.0
  audioplayers: ^5.0.0  # Reproducción de audios
  path_provider: ^2.1.0  # Directorios del dispositivo
  dio: ^5.4.0  # Descarga de archivos con progreso

  flutter_local_notifications: ^17.0.0

  shared_preferences: ^2.2.3
  get: ^4.6.6
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  image: ^4.1.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
